# Generated by Django 4.2.13 on 2024-05-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='violationCondition',
        ),
    ]
