# Generated by Django 4.2.9 on 2024-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_violationcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='address_img',
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_img',
            field=models.ImageField(default='img/unknown.png', upload_to='violation_img'),
        ),
    ]
