# Generated by Django 4.2.9 on 2024-05-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_violation_address_img_violation_violation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('تنفيذ شبكة', 'Network'), ('عداد', 'Counter'), ('طوارئ', 'Emergency'), ('إحلال', 'Substitute'), ('التعزيز', 'Reinforcement'), ('الجهد المتوسط', 'Effort'), ('مشروع', 'Projects')], max_length=50),
        ),
    ]
