# Generated by Django 4.2.9 on 2024-05-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_pdf_file_name_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('تنفيذ شبكة', 'Network'), ('عداد', 'Counter'), ('طوارئ', 'Emergency'), ('إحلال', 'Substitute'), ('التعزيز', 'Reinforcement'), ('الجهد المتوسط', 'Effort'), ('مشروع', 'Projects'), ('ملفات جاهزة', 'Readyfiles')], max_length=50),
        ),
    ]
